HeThongTinTuc/Models/bantin.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HeThongTinTuc.Models
{
    public class bantin
    {
        public int bantinid { get; set; }
        [Display(Name = "Chuyên Mục")]
        public int chuyenmucid { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tiêu đề.")]
        [Display(Name = "Tiêu đề")]
        public string tieude { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tóm tắt.")]
        [Display(Name = "Tóm tắt")]
        public string tomtat { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập nội dung.")]
        [Display(Name = "Nội dung")]
        public string noidung { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Ngày đăng")]
        public DateTime ngaydang { get; set; }
        [Display(Name = "Người đăng")]
        public string nguoidang { get; set; }
        [Display(Name = "Hình ảnh")]
        public string hinhanh { get; set; }
        [Display(Name = "Tiêu đề hình ảnh")]
        public string tieudehinh { get; set; }
        [Display(Name = "Lượt xem")]
        public int luotxem { get; set; }
        [Display(Name = "Tin nổi bật")]
        public bool noibat { get; set; }
        [Display(Name = "Trạng thái")]
        public bool kichhoat { get; set; }
        [Display(Name = "Chuyên mục")]
        public chuyenmuc chuyenmuc { get; set; }
        
    }
}

HeThongTinTuc/Controllers/bantinController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HeThongTinTuc.Data;
using HeThongTinTuc.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace HeThongTinTuc.Controllers
{
    [Authorize]
    public class bantinController : Controller
    {
        private readonly ApplicationDbContext _context;

        public bantinController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: bantin
        public async Task<IActionResult> Index(string Searching = "")
        {
            if (Searching == null)
            {
                return View(await _context.bantin.ToListAsync());
            }
            return View(await _context.bantin.Where(n => (n.tieude.Contains(Searching))).ToListAsync());
        }

        // GET: bantin/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bantin = await _context.bantin
                .FirstOrDefaultAsync(m => m.bantinid == id);
            if (bantin == null)
            {
                return NotFound();
            }

            return View(bantin);
        }

        // GET: bantin/Create
        public IActionResult Create()
        {
            ViewData["chuyenmucid"] = new SelectList(_context.chuyenmuc, "chuyenmucid", "tenchuyenmuc");
            return View();
        }

        // POST: bantin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile file ,[Bind("bantinid,chuyenmucid,tieude,tomtat,noidung,ngaydang,nguoidang,hinhanh,tieudehinh,luotxem,noibat,kichhoat")] bantin bantin)
        {
            if (ModelState.IsValid)
            {
                bantin.hinhanh = Upload(file);
                _context.Add(bantin);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bantin);
        }

        // GET: bantin/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bantin = await _context.bantin.FindAsync(id);
            if (bantin == null)
            {
                return NotFound();
            }
            ViewData["chuyenmucid"] = new SelectList(_context.chuyenmuc, "chuyenmucid", "tenchuyenmuc", bantin.chuyenmucid);
            return View(bantin);
        }

        // POST: bantin/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IFormFile file, int id, [Bind("bantinid,chuyenmucid,tieude,tomtat,noidung,ngaydang,nguoidang,hinhanh,tieudehinh,luotxem,noibat,kichhoat")] bantin bantin)
        {

            if (id != bantin.bantinid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (file != null)
                    {
                        bantin.hinhanh = Upload(file);
                    }
                    _context.Update(bantin);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!bantinExists(bantin.bantinid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bantin);
        }

        // GET: bantin/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bantin = await _context.bantin
                .Include(b => b.chuyenmuc)
                .FirstOrDefaultAsync(m => m.bantinid == id);
            if (bantin == null)
            {
                return NotFound();
            }

            return View(bantin);
        }

        // POST: bantin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bantin = await _context.bantin.FindAsync(id);
            _context.bantin.Remove(bantin);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool bantinExists(int id)
        {
            return _context.bantin.Any(e => e.bantinid == id);
        }

        public string Upload(IFormFile file)
        {
            string uploadFileName = null;
            if (file != null)
            {
                //Phát sinh tên
                uploadFileName = Guid.NewGuid().ToString() + "_" + file.FileName;
                var path = $"wwwroot\\images\\{uploadFileName}";
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    file.CopyTo(stream);
                }
            }
            return uploadFileName;
        }
    }
}

HeThongTinTuc/Views/bantin/Create.cshtml
@model HeThongTinTuc.Models.bantin

@{
    ViewData["Title"] = "Create";
}

<h1>Thêm Bản Tin</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="chuyenmucid" class="control-label"></label>
                <select asp-for="chuyenmucid" class ="form-control" asp-items="ViewBag.chuyenmucid"></select>
            </div>
            <div class="form-group">
                <label asp-for="tieude" class="control-label"></label>
                <textarea asp-for="tieude" class="form-control" ></textarea>
                <span asp-validation-for="tieude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tomtat" class="control-label"></label>
                <textarea asp-for="tomtat" class="form-control" ></textarea>
                <span asp-validation-for="tomtat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="noidung" class="control-label"></label>
                <textarea asp-for="noidung" class="form-control" ></textarea>
                <span asp-validation-for="noidung" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ngaydang" class="control-label"></label>
                <input asp-for="ngaydang" class="form-control" />
                <span asp-validation-for="ngaydang" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nguoidang" class="control-label"></label>
                <input asp-for="nguoidang" class="form-control" />
                <span asp-validation-for="nguoidang" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="hinhanh" class="control-label"></label>
                <input type="file" name="file" />
                <span asp-validation-for="hinhanh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tieudehinh" class="control-label"></label>
                <textarea asp-for="tieudehinh" class="form-control" ></textarea>
                <span asp-validation-for="tieudehinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="luotxem" class="control-label"></label>
                <input asp-for="luotxem" class="form-control" />
                <span asp-validation-for="luotxem" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="noibat" /> @Html.DisplayNameFor(model => model.noibat)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="kichhoat" /> @Html.DisplayNameFor(model => model.kichhoat)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HeThongTinTuc/Views/bantin/Delete.cshtml
@model HeThongTinTuc.Models.bantin

@{
    ViewData["Title"] = "Delete";
}

<h1>Xóa Bản Tin</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>bantin</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tieude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tieude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tomtat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tomtat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.noidung)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.noidung)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ngaydang)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ngaydang)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nguoidang)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nguoidang)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.hinhanh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.hinhanh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tieudehinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tieudehinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.luotxem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.luotxem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.noibat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.noibat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.kichhoat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.kichhoat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.chuyenmuc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.chuyenmuc.tenchuyenmuc)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="bantinid" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HeThongTinTuc/Views/bantin/Details.cshtml
@model HeThongTinTuc.Models.bantin

@{
    ViewData["Title"] = "Details";
}

<h1 class="text-primary">Chi Tiết Bản Tin</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tieude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tieude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tomtat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tomtat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.noidung)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.noidung)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ngaydang)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ngaydang)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nguoidang)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nguoidang)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.hinhanh)
        </dt>
        <dd class="col-sm-10">
            <img src="~/images/@Html.DisplayFor(model => model.hinhanh)" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tieudehinh)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tieudehinh)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.luotxem)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.luotxem)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.noibat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.noibat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.kichhoat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.kichhoat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.chuyenmuc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.chuyenmuc.tenchuyenmuc)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.bantinid">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

HeThongTinTuc/Views/bantin/Edit.cshtml
@model HeThongTinTuc.Models.bantin

@{
    ViewData["Title"] = "Edit";
}

<h1>Sửa Bản Tin</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="bantinid" />
            <div class="form-group">
                <label asp-for="chuyenmucid" class="control-label"></label>
                <select asp-for="chuyenmucid" class="form-control" asp-items="ViewBag.chuyenmucid"></select>
                <span asp-validation-for="chuyenmucid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tieude" class="control-label"></label>
                <textarea asp-for="tieude" class="form-control" ></textarea>
                <span asp-validation-for="tieude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tomtat" class="control-label"></label>
                <textarea asp-for="tomtat" class="form-control" ></textarea>
                <span asp-validation-for="tomtat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="noidung" class="control-label"></label>
                <textarea asp-for="noidung" class="form-control" ></textarea>
                <span asp-validation-for="noidung" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ngaydang" class="control-label"></label>
                <input asp-for="ngaydang" class="form-control" />
                <span asp-validation-for="ngaydang" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="nguoidang" class="control-label"></label>
                <input asp-for="nguoidang" class="form-control" />
                <span asp-validation-for="nguoidang" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="hinhanh" class="control-label"></label>
                <input type="file" name="file" />
                <span asp-validation-for="hinhanh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="tieudehinh" class="control-label"></label>
                <textarea asp-for="tieudehinh" class="form-control" ></textarea>
                <span asp-validation-for="tieudehinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="luotxem" class="control-label"></label>
                <input asp-for="luotxem" class="form-control" />
                <span asp-validation-for="luotxem" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="noibat" /> @Html.DisplayNameFor(model => model.noibat)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="kichhoat" /> @Html.DisplayNameFor(model => model.kichhoat)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HeThongTinTuc/Views/bantin/Index.cshtml
@model IEnumerable<HeThongTinTuc.Models.bantin>

@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-8 my-3">
        <h2 class="text-primary">Danh Sách Bản Tin</h2>
    </div>
    <div class="col-4 my-3">
        <div class="row ">
            @using (Html.BeginForm("Index", "bantin"))
            {
                <p class="fsearch input-group m-1 p-1">
                    @Html.TextBox("Searching", "", new { @class = "fs border-primary rounded-left" })
                    <button class="btn btn-primary" type="submit">Tìm Kiếm</button>
                </p>
            }
        </div>
    </div>
</div>

<p>
    <a asp-action="Create" class="btn btn-outline-info">Create New</a>
</p>
<table class="table" style="border: 1px">
    <thead>
        <tr class="text-dark text-center" style="background-color:yellow">
            <th width="2%">
                @Html.DisplayNameFor(model => model.tieude)
            </th >
            <th width="3%">
                @Html.DisplayNameFor(model => model.tomtat)
            </th>
            <th >
                @Html.DisplayNameFor(model => model.noidung)
            </th>
            <th width="8%">
                @Html.DisplayNameFor(model => model.ngaydang)
            </th>
            <th width="2%">
                @Html.DisplayNameFor(model => model.nguoidang)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.hinhanh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tieudehinh)
            </th>
            <th width="3%">
                @Html.DisplayNameFor(model => model.luotxem)
            </th>
            <th width="3%">
                @Html.DisplayNameFor(model => model.noibat)
            </th>
            <th width="3%">
                @Html.DisplayNameFor(model => model.kichhoat)
            </th>
            <th width="7%">
                @Html.DisplayNameFor(model => model.chuyenmuc)
            </th>
            <th width="5%"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.tieude)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tomtat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.noidung)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ngaydang)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nguoidang)
                </td>
                <td>
                    <img src="~/images/@Html.DisplayFor(modelItem => item.hinhanh)" width="50" class="img-thumbnail" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tieudehinh)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.luotxem)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.noibat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.kichhoat)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.chuyenmuc.tenchuyenmuc)
                </td>
                <td>
                    <a class="btn btn-outline-warning" asp-action="Edit" asp-route-id="@item.bantinid">Edit</a>
                    <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.bantinid">Details</a>
                    <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.bantinid">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>