HeThongTinTuc/Models/chuyenmuc.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace HeThongTinTuc.Models
{
    public class chuyenmuc
    {
        public int chuyenmucid { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên chuyên mục.")]
        [Display(Name = "Tên chuyên mục")]
        public string tenchuyenmuc { get; set; }
        [Display(Name = "Thứ tự")]
        public int thutu { get; set; }
        public ICollection<bantin> bantins { get; set; }
    }
}

HeThongTinTuc/Controllers/chuyenmucController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HeThongTinTuc.Data;
using HeThongTinTuc.Models;
using Microsoft.AspNetCore.Authorization;

namespace HeThongTinTuc.Controllers
{
    [Authorize]
    public class chuyenmucController : Controller
    {
        private readonly ApplicationDbContext _context;

        public chuyenmucController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: chuyenmuc
        public async Task<IActionResult> Index(string Searching = "")
        {
            if (Searching == null)
            {
                return View(await _context.chuyenmuc.ToListAsync());
            }
            return View(await _context.chuyenmuc.Where(n => (n.tenchuyenmuc.Contains(Searching))).ToListAsync());
        }

        // GET: chuyenmuc/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chuyenmuc = await _context.chuyenmuc
                .FirstOrDefaultAsync(m => m.chuyenmucid == id);
            if (chuyenmuc == null)
            {
                return NotFound();
            }

            return View(chuyenmuc);
        }

        // GET: chuyenmuc/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: chuyenmuc/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("chuyenmucid,tenchuyenmuc,thutu")] chuyenmuc chuyenmuc)
        {
            if (ModelState.IsValid)
            {
                _context.Add(chuyenmuc);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(chuyenmuc);
        }

        // GET: chuyenmuc/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chuyenmuc = await _context.chuyenmuc.FindAsync(id);
            if (chuyenmuc == null)
            {
                return NotFound();
            }
            return View(chuyenmuc);
        }

        // POST: chuyenmuc/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("chuyenmucid,tenchuyenmuc,thutu")] chuyenmuc chuyenmuc)
        {
            if (id != chuyenmuc.chuyenmucid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(chuyenmuc);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!chuyenmucExists(chuyenmuc.chuyenmucid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(chuyenmuc);
        }

        // GET: chuyenmuc/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var chuyenmuc = await _context.chuyenmuc
                .FirstOrDefaultAsync(m => m.chuyenmucid == id);
            if (chuyenmuc == null)
            {
                return NotFound();
            }

            return View(chuyenmuc);
        }

        // POST: chuyenmuc/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var chuyenmuc = await _context.chuyenmuc.FindAsync(id);
            _context.chuyenmuc.Remove(chuyenmuc);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool chuyenmucExists(int id)
        {
            return _context.chuyenmuc.Any(e => e.chuyenmucid == id);
        }
    }
}

HeThongTinTuc/Views/chuyenmuc/Create.cshtml
@model HeThongTinTuc.Models.chuyenmuc

@{
    ViewData["Title"] = "Create";
}

<h1>Thêm Chuyên Mục</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="tenchuyenmuc" class="control-label"></label>
                <input asp-for="tenchuyenmuc" class="form-control" />
                <span asp-validation-for="tenchuyenmuc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="thutu" class="control-label"></label>
                <input asp-for="thutu" class="form-control" />
                <span asp-validation-for="thutu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HeThongTinTuc/Views/chuyenmuc/Delete.cshtml
@model HeThongTinTuc.Models.chuyenmuc

@{
    ViewData["Title"] = "Delete";
}

<h1>Xóa Chuyên Mục</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.tenchuyenmuc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.tenchuyenmuc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.thutu)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.thutu)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="chuyenmucid" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

HeThongTinTuc/Views/chuyenmuc/Edit.cshtml
@model HeThongTinTuc.Models.chuyenmuc

@{
    ViewData["Title"] = "Edit";
}

<h1>Sửa Chuyên Mục</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="chuyenmucid" />
            <div class="form-group">
                <label asp-for="tenchuyenmuc" class="control-label"></label>
                <input asp-for="tenchuyenmuc" class="form-control" />
                <span asp-validation-for="tenchuyenmuc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="thutu" class="control-label"></label>
                <input asp-for="thutu" class="form-control" />
                <span asp-validation-for="thutu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

HeThongTinTuc/Views/chuyenmuc/Index.cshtml
@model IEnumerable<HeThongTinTuc.Models.chuyenmuc>

@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="col-8 my-3">
        <h2 class="text-primary">Danh Sách Chuyên Mục</h2>
    </div>
    <div class="col-4 my-3">
        <div class="row ">
            @using (Html.BeginForm("Index", "chuyenmuc"))
            {
                <p class="fsearch input-group m-1 p-1">
                    @Html.TextBox("Searching", "", new { @class = "fs border-primary rounded-left" })
                    <button class="btn btn-primary" type="submit">Tìm Kiếm</button>
                </p>
            }
        </div>
    </div>
</div>

<p>
    <a asp-action="Create" class="btn btn-outline-info">Create new</a>
</p>
<table class="table" style="border: 1px">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.thutu)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.tenchuyenmuc)
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.thutu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tenchuyenmuc)
            </td>

            <td>
                <a class="btn btn-outline-warning" asp-action="Edit" asp-route-id="@item.chuyenmucid">Edit</a> |
                <a class="btn btn-outline-danger" asp-action="Delete" asp-route-id="@item.chuyenmucid">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>